name: electra-pretrain
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.5.5
  - ipykernel
  - jupyter
  - pip
  - sqlalchemy
  - psycopg2
  - pandas
  - html2text
  - nltk
  - tqdm
  - transformers
  - pytorch
